README.md
src/utils/api/tracker.test.js
src/utils/api/tracker.ts

Related change: https://github.com/streamr-dev/streamr-client-protocol-js/pull/48

Add partition option to getTrackerForStream

---

.github/workflows/nodejs.yml

Trying out Github actions, this runs lint & test and builds the project - seems pretty straightforward. 
The Docker build goes through Travis but that could be moved into an action as well (eg. https://github.com/streamr-dev/broker/blob/7ac0deb87e00045918b5d0e5756539b69aa16acc/.github/workflows/nodejs.yml#L41)

Set up Github action for linting & testing

---

package-lock.json
package.json
src/app/App.tsx
src/components/Debug/index.tsx
src/components/Layout.tsx
src/components/Map/index.tsx
src/types/react-pretty-json/react-pretty-json.d.ts

Hides debug view into the top right corner:

[FRONT-194] More inconspicuous debug view

---

src/components/Map/index.tsx

Adds debouncing for the map's `setViewport` method. It seems to go out of sync when active node was being set. I could only reproduce this with a stream that has only one node in the topology like this:
```js
{
[0x123...567]: [],
}
```
Anyway, should fix the problem.

[FRONT-166] Fix clicking on network node crashes map

---

src/components/Map/index.tsx
src/components/SearchBox/SearchResults.tsx
src/components/SearchBox/index.tsx
src/contexts/Controller.tsx
src/contexts/Store.tsx
src/utils/api/mapbox.ts
src/utils/api/streamr.ts

On top of #26 
Adds jumping to specific map location. It doesn't close the search after clicking since there is no route for places like streams and nodes. A bit inconsistent but seems better to use.

[FRONT-207] Fly to map location

---

src/components/NodeList/NodeListItem.tsx
src/components/SearchBox/Search.tsx
src/components/SearchBox/SearchBox.stories.tsx
src/components/SearchBox/index.tsx
src/components/Stats.stories.tsx
src/components/Stats.tsx

On top of #26, adds animation and fading to stat labels.

[FRONT-208] Add hover state to stat labels

---

src/components/SearchBox/SearchInput.tsx
src/components/SearchBox/SearchResults.tsx
src/components/SearchBox/index.tsx
src/components/Stream/TopologyList.tsx
src/utils/text.ts

* Don't allow selecting stat label when results are active
* Show truncated stream path in stream topology list
* Show truncated path in search box when not focused

[FRONT-199] Searchbox improvements

---

src/app/App.tsx
src/components/Graphs/EventsPerSecond.tsx
src/components/Graphs/Graphs.stories.tsx
src/components/Graphs/index.tsx
src/components/LoadingIndicator/LoadingIndicator.stories.tsx
src/components/LoadingIndicator/index.tsx

Add loading indicator to events per second graph:
https://user-images.githubusercontent.com/1064982/103406581-d73ee180-4b63-11eb-87d9-2854bdebfc60.mov

[FRONT-182] Graph loading state

---

src/components/Error.tsx
src/components/Graphs/EventsPerSecond.tsx
src/components/Graphs/Graphs.tsx
src/components/Graphs/Intervals.tsx
src/components/Graphs/Loading.tsx
src/components/Graphs/index.tsx
src/components/Node/TopologyList.tsx
src/components/NodeList/NodeList.stories.tsx
src/components/NodeList/NodeListItem.tsx
src/components/NodeList/index.tsx
src/components/SearchBox/SearchBox.stories.tsx
src/components/Stats.tsx
src/components/Stream/TopologyList.tsx

Adds an error notice to nodes and network stream metrics:

[FRONT-222] Add error component for node & search list

---

.github/workflows/ci.yml
Dockerfile

Adds npm authentication to Dockerfile.

[FRONT-300] Fix Docker build

---

.storybook/main.js
config-overrides.js
package-lock.json
package.json

Fixes storybook build, also removes the console.log that was printing the config (I first thought it was a warning 🙄)

Use config overrides in storybook build

---

package-lock.json
package.json
src/components/Node/TopologyList.tsx
src/components/NodeList/NodeList.stories.tsx
src/components/NodeList/NodeListItem.tsx
src/components/Stream/TopologyList.tsx

Add animation to node list item:
https://user-images.githubusercontent.com/1064982/113861894-69cccd80-97b0-11eb-8ff6-21ac8e97382a.mov

[FRONT-328] Node tiles animation

---

package-lock.json
package.json
src/components/Graphs/TimeSeries.tsx
src/components/Graphs/TimeSeriesGraph.stories.tsx
src/components/MetricGraph.tsx

Added formatter function prop to `TimeSeries` component to display the node MB/s stats consistently.

[FRONT-399] TimeSeries hovered value format

---

src/components/Debug/index.tsx
src/utils/envs.ts

Makes debug window draggable, store position in local storage.

Add draggable debug window, set testnet streamr api url

---

src/components/NodeList/NodeListItem.tsx

> Should be Plex Sans, is Plex Mono. Also please pay attention to letterspacing. All caps text will almost always have non-zero letterspacing.

[FRONT-476] Typeface in NE Eth address display is incorrect

---

src/components/NodeList/NodeListItem.tsx
src/components/NodeList/index.tsx
src/components/Stream/TopologyList.tsx

Scrolls to show currently selected node in the stream view.

[FRONT-527] Scroll to show active node in list

---

src/components/Map/NavigationControl.tsx
src/components/NodeList/NodeList.stories.tsx
src/components/NodeList/Pager.tsx
src/components/NodeList/index.tsx
src/components/Stream/TopologyList.tsx
src/components/Stream/index.tsx
src/contexts/Controller.tsx
src/hooks/usePaged.ts
src/utils/styled.ts

Add paging to node list. The layout is copied from the partition section in design.. needs at least a new icon:
@mattatgit Could you throw an eye on this?

Add paged node list

---

src/contexts/Controller.tsx

Small fix to keep the pending status alive while search is going on. Previously if you started a search and then started typing again, the pending status would complete before the results would arrive.

Keep pending status alive even if request is cancelled

---

src/utils/config.test.js
src/utils/config.ts
src/utils/envs.ts

Add ability to select a `streamr` config at random, value is cached so it will be chosen only once.

Select random streamr config

---

src/components/SearchBox/NoSearchResults.tsx
src/components/SearchBox/Search.tsx
src/components/SearchBox/SearchBox.stories.tsx
src/components/SearchBox/index.tsx

We'll show a hint box when there are no search results.

[FRONT-532] Empty search results hint box

---

src/components/Map/ConnectionLayer.tsx
src/components/Map/index.tsx

If a single node is selected, we'll show only the connections for that node.

[FRONT-526] Single node selection connections
