streamr-dev/network-explorer

src/components/SearchBox/SearchResults.tsx, src/components/SearchBox/useSearch.test.tsx, src/components/SearchBox/useSearch.ts, src/utils/api/mapbox.ts, src/utils/api/streamr.ts
Update search box so that it handles overflow + styled list items.
=> [FRONT-186] Network explorer search box long result list breaks layout

src/app/App.tsx, src/components/Map/index.tsx, src/components/Node/TopologyList.tsx, src/components/Node/index.tsx, src/components/NodeList/index.tsx, src/components/Stream/TopologyList.tsx, src/contexts/Controller.tsx
Add default display of all nodes on the map when nothing is selected.
Also should fix zooming issue ([FRONT-196](https://linear.app/streamr/issue/FRONT-196/zoom-levels-for-nodes-are-too-high)), basically when `activeNode` is defined it should react to that and when not, it should zoom the topology into view.
=> [FRONT-195] Show all nodes in default view

package.json, src/components/Node/index.tsx, src/components/Stream/index.tsx, src/contexts/Controller.test.jsx, src/contexts/Controller.tsx, src/contexts/Store.test.jsx, src/utils/api/streamr.test.js, src/utils/api/streamr.ts, src/utils/api/tracker.test.js, src/utils/api/tracker.ts
Loads topology in default view from all trackers, using the `/node-connections/` endpoint. This returns all the nodes and their connections.
You'll need to update your Docker env to latest for the endpoint to work.
=> [FRONT-200] Load default view topology

src/components/Highlight/Hightlight.stories.tsx, src/components/Highlight/index.tsx, src/components/SearchBox/Search.tsx, src/components/SearchBox/SearchBox.stories.tsx, src/components/SearchBox/SearchResults.tsx, src/components/SearchBox/index.tsx
> Give the icons a background box
> 
> Each search result needs a 2 line layout. 1st line is search result name, 2nd is stream ID (or path) or category such as "Place" etc
> 
> Use 8pts of padding between top & bottom edge of each section
Tweak result list UI in desktop, add highlighting of search term:
=> [FRONT-216] Network Explorer search results view improvements

src/components/Map/Markers.tsx
Nodes (and clusters) are now 24px (down from 32px) in size. Identicon is shown at all times for nodes and when a node is selected, it will grow to 32px and gain a blue border.
=> [FRONT-224] Update node styling

src/components/Map/NavigationControl.tsx, src/components/Map/index.tsx, src/components/Map/utils.tsx, src/hooks/useKeyDown.ts
Added custom zoom controls with new icons. Also added a reset button.
PS. You can reset the map also with keyboard key `0`
=> [FRONT-223] Add custom zoom controls and map reset functionality

src/app/App.tsx, src/components/Map/index.tsx, src/components/Node/TopologyList.tsx, src/components/Node/index.tsx, src/components/NodeList/NodeList.stories.tsx, src/components/NodeList/NodeListItem.tsx, src/components/NodeList/index.tsx, src/components/SearchBox/index.tsx, src/contexts/Store.test.jsx, src/contexts/Store.tsx
Fix:
> Node eth addresses are not following standard centre-truncation rules
>
> streams cannot be unloaded by clearing the search
- unload stream when clearing search
- When searching for node, node title is not shown in search
- Show only the active node in default view
- Don't zoom to active node anymore
=> [FRONT-217] Show only active node in default view, unload stream on search clear

src/components/Stream/index.tsx
Stream path was set to search field only when searching. If the stream is selected and page is refreshed, the search was empty, this add stream path to search by default.
=> [FRONT-236] Set stream name to search field when loading a stream

src/components/Map/Map.stories.tsx, src/components/Map/NavigationControl.tsx, src/components/Map/index.tsx, src/components/SearchBox/Search.tsx
Fixes broken `Map` storybook story, I moved the `useStore` hook out from `NavigationControl` into the connected parent component so the Map component can stay "dumb".
=> Move store from NavigationControl to parent component

src/components/Map/ConnectionLayer.tsx, src/components/Map/Map.stories.tsx, src/components/Map/MarkerLayer.tsx, src/components/Map/index.tsx, src/utils/api/tracker.ts
Add feature for expanding clusters that have overlapping nodes inside:
@mattatgit: This probably needs a design pass? Should we add lines pointing to the center point?
Also fixes problem with node connection drawing that made the connections disappear if either of the connected nodes was out of viewport.
PS. I noticed that nodes seem not to form a perfect circle for some reason. Anyone can spot why x-axis looks like it's squashed a bit.
=> [FRONT-197][FRONT-70] Add expansion of clusters that have overlapping nodes

src/components/Graphs/Graphs.stories.tsx, src/components/Graphs/Intervals.tsx, src/components/Node/TopologyList.tsx, src/components/NodeList/NodeListItem.tsx, src/components/NodeStats.tsx, src/components/Stream/TopologyList.tsx
Adds loading of metrics stream to nodes when clicking on the stats. It loads the stream data first before making a subscription, in case the stream doesn't exist (which it doesn't atm).
=> Add metric stream loading to nodes

src/components/SearchBox/SearchBox.stories.tsx, src/components/SearchBox/SearchResults.tsx
Improve stream path truncation in the search results, long paths are now displayed so that the last fragment is not truncated, only the part before it:
=> [FRONT-260] Improve search result truncation

package-lock.json, package.json, src/components/Map/index.tsx
Update map style + downgrade typescript version to get rid of `eslint` warning
=> [FRONT-293] Update map style, typescript version

src/utils/api/tracker.ts, src/utils/config.ts, src/utils/envs.ts
Enables running a mock API along with the `local` and `production` options.
To make it work:
- install the mock API here: https://github.com/streamr-dev/network-explorer-mock-api
- run `npm ci` and `npm start`, mock api starts in port 3001
- Run the app and select `mock-api` from the debug window
=> [FRONT-302] Enable mock data API

src/components/StreamStats.tsx, src/utils/api/tracker.ts
There was an error with the `getIndexedNodes` calculation, this (and the previous) code is adapted from https://github.com/streamr-dev/quick-dijkstra/blob/1.1.0/examples/wasm/typescript-webpack/src/explorerconverter.ts
=> Fix indexed nodes calculation

src/components/Map/ConnectionLayer.tsx, src/components/Map/Map.stories.tsx, src/components/Map/NavigationControl.tsx, src/components/Map/index.tsx, src/contexts/Store.test.jsx, src/contexts/Store.tsx
Adds node connections toggle to map navigation control. By default, does not show topology in main page but in stream page it does.
FYI, navigation control position in mobile handled in #53
=> [FRONT-296] Add node connection toggle

src/components/Map/NavigationControl.tsx, src/components/Map/Tooltip.tsx
Fixes:
* Add tooltips to reset and node connections toggle
* Separate connection and reset button from Zoom in / out buttons
* Connection button blue click state
* Fix Connection widget icon size
=> [FRONT-326] Map controls styling

src/app/App.tsx, src/components/Map/ConnectionLayer.tsx, src/components/Map/index.tsx, src/components/Node/index.tsx, src/components/SearchBox/SearchBox.stories.tsx, src/components/SearchBox/SearchInput.tsx, src/components/SearchBox/index.tsx, src/components/Stream/index.tsx
Fixes:
* Connection lines should be 50% opacity
* Deselecting a node. Added deselect by clicking anywhere on the map (except on another node). Clicking again on the same node should also deselect. If you select a node, it should also show in the search box.
* Change cursor when dragging map, default cursor is `default` (standard pointer), on drag `all-scroll` (4 way arrow)
Seems that cursor change does not work in Safari where it changes to text cursor when dragging.
=> [FRONT-327] Map view updates

src/app/App.tsx, src/components/Node/TopologyList.tsx, src/components/SearchBox/index.tsx, src/components/Stream/TopologyList.tsx
Multiple WebSocket connections were opened before this change.
=> [FRONT-398] Use single StreamrClientProvider

src/components/Stats.tsx
> Captions (MSGS / SEC etc) & numbers aren’t centred in each section, as you can see from the Staging images: numbers and blue underlines are not aligned. The problem seems to be the same in both the Global display & individual node display
Fixes metrics underline display alignment.
=> [FRONT-420] Fix metrics underline display alignment

src/components/Graphs/Graphs.tsx, src/components/Graphs/Intervals.tsx, src/components/MetricGraph.tsx
Add a realtime graph option that displays the `sec` stream in a 10 minute window. I had to change the labels a bit to fit all:
=> Add realtime graph

src/components/Graphs/TimeSeries.tsx, src/components/Graphs/TimeSeriesGraph.stories.tsx, src/components/MetricGraph.tsx
Add sorting to incoming metric data to avoid messed upped looking graphs. I think when that happens the data points are coming out of order and the graph goes crazy. Also added a data domain for the X-axis, that seems to do some sorting as well.
=> [FRONT-416] Sort graph data

src/components/Map/Map.stories.tsx, src/components/Map/index.tsx, src/components/MetricGraph.tsx, src/components/Node/TopologyList.tsx, src/components/Node/index.tsx, src/components/NodeList/NodeList.stories.tsx, src/components/NodeList/NodeListItem.tsx, src/components/NodeStats.tsx, src/components/SearchBox/index.tsx, src/components/Stream/TopologyList.tsx, src/components/Stream/index.tsx, src/utils/api/tracker.test.js, src/utils/api/tracker.ts
There was a change in the tracker API that added a randomly generated session id as part of the node id to disambiguate nodes running with the same private key. The format is `[address]#[sessionId]` (eg. `0xE698e1aeC4F099c50B9408f23AeaF3f0892147a1#3c6bbccc-4aca-4a82-aea5-59ea7ae1761e`).
We have to parse the address from the incoming `id` and use URL encoding/decoding whenever referencing this in links. However, node specific metric streams will still be referenced with the address, not id.
=> Parse node address

src/app/App.tsx, src/components/Debug/index.tsx, src/components/Map/NavigationControl.tsx, src/components/NetworkSelector/index.tsx, src/components/SearchBox/SearchInput.tsx, src/components/Tooltip.tsx, src/utils/config.test.js, src/utils/config.ts, src/utils/envs.ts
Add network selector to upper right corner. Debug view is now hidden unless `network-eplorer.debug` variable is set in local storage.
Use `http://[explorer url]/?network=production` to link directly to a network
=> [FRONT-448] Implement Network selector dropdown

src/components/NetworkSelector/index.tsx, src/components/Tooltip.tsx
> The only way to close it is to click the icon again. Not good UX, we need to give users multiple common paths to do this
>
> * clicking on the map background
> * hitting the esc key on keyboard
> * clicking the selector icon
Improve closing of the network selector. Also hide tooltip while dropdown is open.
=> [FRONT-475] Improve network selector closing

src/contexts/Store.tsx
Active node effect was not visible on map when reloaded page with nodeId in URL. Now it is fixed.
=> [FRONT-520] Update active node when nodes change

src/components/Map/index.tsx
Set viewport to contain most of northern hemisphere. Also disables fitting nodes to viewport. This is wanted to make initial load as smooth as possible and not have automatic zooming.
=> [FRONT-511] Wider default viewport

src/components/Map/MarkerLayer.tsx, src/components/Map/index.tsx
This PR uses a GeoJSON circle layer to draw node markers on map. Rendering perfomance is greatly improved this way. We'll need to use Mapbox feature states to control hover and active styles for nodes.
Note that we'll lose smooth CSS transitions for hover and active states. Mapbox should support transitions for style changes but I could not make it work. Let's see later if we can add animations.
=> [FRONT-543] Use GeoJSON layer for node markers

src/contexts/Controller.tsx, src/contexts/Store.tsx, src/utils/api/tracker.ts
Improves speed by getting rid of `.reduce` in data methods, this seemed to be the bottle in the browser... This already helps a lot.
=> Use for loops instead of .reduce for node mappings

.github/workflows/ci.yml
This PR defines shell as `bash` and concurrency rules for Pull Requests.
When working on PR and pushing a single commit to branch that activates the CI build and then immediately pushing a new commit to the same branch will cancel the build started by the previous push.
=> ci: add concurrency and default shell

src/components/Layout.tsx, src/components/Network/TopologyList.tsx, src/components/Network/index.tsx, src/components/NodeList/index.tsx, src/components/Stream/TopologyList.tsx
When clicking on a node in the whole network view, list all nodes with the same longitude and latitude. There is a bit of a jump when choosing an active node but it will scroll to the active spot. Also clicking on an active node won't collapse it as that would hide the whole list. There is some room for UX improvement there 😈
=> [FRONT-636] Show list of nodes in the same location

.github/workflows/deploy_production.yml
Purpose of this PR is to make use of the [GitHub Environments](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment) for deployments and to provide a view to [deployment history](https://docs.github.com/en/actions/deployment/managing-your-deployments/viewing-deployment-history).
Concurrency rules for production deployment currently define that the most recent deployment will cancel the currently in progress deployment.
Later [Environment Protection Rules](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#environment-protection-rules) can be used if deemed useful.
=> ci: use production environment

src/components/MapConnectionLayer.tsx, src/components/MapNavigationControl.tsx, src/utils/index.tsx
I enhanced connection visibility logic to show connections when:
- ConnectionsMode is Always, OR
- A stream is selected, OR
- A node is selected
I also added visual feedback for connection toggle button (blue when active) and optimized `useNodeConnections` hook with early returns and proper dependency tracking.
=> [FRONT-1872] Make connection drawing smarter

package-lock.json, package.json, src/Store.tsx, src/components/App.tsx, src/components/MapMarkerLayer.tsx, src/components/NetworkSelector/index.tsx, src/components/NodeTopologyList.tsx, src/components/Stats.tsx, src/components/StreamTopologyList.tsx, src/components/StreamrClientProvider.tsx, src/getters.tsx, src/utils/chains.ts, src/utils/index.tsx, src/utils/neighbors.tsx, src/utils/nodes.ts, src/utils/places.ts, src/utils/queries.ts, src/utils/search.ts, src/utils/streams.ts
This PR adds support for Polygon Amoy network.
- Added network selector UI component with Mainnet/Amoy options
- Implemented selected chain persistence in localStorage
- Updated API clients and queries to use chain-specific endpoints
- Added chain-specific StreamrClient configuration
=> [FRONT-1871] Polygon Amoy support
